### ISSUE TITLE
css style are not render properly

### ISSUE THREAD

**Issue by vitaminac** [MoePlayer/angular-moeplayer#1]
As some style are only apply on div element, it requires that container need to be div element instead of 
 component's name, <code>\<d-player\></code>

The video aren't properly rendered as I expected, play button volume and the rest and wrongly place..

 
![2018-09-06](https://user-images.githubusercontent.com/11367542/45171296-4c06e880-b202-11e8-8c6f-a55947e5259c.png)

After I have change <code>\<d-player\></code> to <code>\<div\></code> in chrome's dev-tools it works.

change component to a directive may be a solution.

**Comment by Guanyunhan** [comment]
Try adding d-player{display: block} to global CSS (style.css)

I will add :host {display: block} to this component in next version

**Comment by vitaminac** [comment]
Thanks, it works. But I prefer this fix can be made into the library just like you said about the next version.

**Comment by Guanyunhan** [comment]
Hello @vitaminac ,  the new version has been updated and released.
